Add justification document describing no stack produced error
thoth-station/thoth-station.github.io pull request #145
Opened 2020-09-18 09:03 UTC by fridex

2020-09-18 09:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex**
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-station.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-station.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2020-09-18 15:24 UTC, goern requested changes

2020-09-18 15:24 UTC, goern commented on _j/no_stack.md
> +title: Resolver did not find any stack that would satisfy requirements and stack characteristics given the time allocated requirements and stack characteristics given the time allocated
there is some repetition...

2020-09-21 10:33 UTC, fridex commented on _j/no_stack.md
> +title: Resolver did not find any stack that would satisfy requirements and stack characteristics given the time allocated requirements and stack characteristics given the time allocated
Thanks, adjusted in 056bd566.

2020-09-22 11:06 UTC, merged